### ISSUE TITLE
AOSC OS MIPS64r6el Stage 2 Progress

### ISSUE THREAD

**Issue by Cyanoxygen** [AOSC-CIP-Pilot/aosc-os-abbs#1]
This issue tracks the tasks completed/pending for a stage 2 (dirty and minmal) AOSC OS BuildKit release. After which, we enter stage 3, when we rebuild the BuildKit recipe using Ciel, producing clean and feature-complete packages.

### Road to Stage 2

- [x] Building AOSC OS Core
- [x] Introducing DPKG
- [x] Introducing APT
- [x] Introducing packages for AOSC OS maintenance toolchain
- [x] Completing the BuildKit recipe 
- [x] Recording Stage 2 recipes (.stage2 support for Autobuild3)
- [x] Committing all manifest/scripting changes

### Key Features (Stage 2)

Introduce key development features (build systems, toolchains, etc.) after `apt` availability is key to simplify dependency introduction during stage 2.

#### Maintenance Toolchain

- [x] autobuild3
- [x] acbs

#### Build Systems

- [x] autoconf
- [x] automake
- [x] cmake 
- [x] gtk-doc
- [x] intltool
- [x] meson
- [x] ninja
- ~pip~ (blocked by Rust, `setuptools-rust`)
- [x] po4a
- [x] python-build
- [x] python-installer
- [x] setuptools
- ~wheel~ (blocked by Rust, `setuptools-rust`)

#### Languages

- [x] C
- [x] C++
- ~Go~ (no architectural support)
- [x] GObject-Introspection
- [x] OCaml
- [x] Perl
- [x] Python 2
- [x] Python 3
- ~Ruby~ (segfaults during build time)
- ~Rust~ (no working version, see below)
- [x] Vala

#### Other Components

- [x] systemd
- [x] x11-lib

### BuildKit Recipe

Dependencies needed to generate a stage 2 BuildKit release.

#### At a Glance

- [x] acbs
- [x] admin-base
- [x] autobuild3
- [x] core-base
- [x] debug-base
- [x] devel-base
- [x] editor-base
- [x] git
- [x] network-base
- [x] python-base
- [x] systemd-base
- [x] util-base
- [x] web-base

#### admin-base

- [x] apt
- [x] apt-file
- ~atm~ (no working Rust version, see below)
- [x] bcache-tools
- [x] btrfs-progs
- [x] cryptsetup
- [x] dbus
- [x] debianutils
- [x] dosfstools
- [x] e2fsprogs
- [x] exfat-utils
- [x] f2fs-tools
- [x] fcron
- [x] fuse
- [x] genfstab
- [x] gnupg
- [x] gpart
- [x] gptfdisk
- [x] hddtemp
- [x] hfsprogs
- [x] jfsutils
- [x] kernel-tools
- [x] mdadm
- [x] mtd-utils
- [x] multipath-tools
- [x] nvme-cli
- [x] os-prober
- [x] parted
- [x] polkit
- [x] powertop
- [x] quota-tools
- [x] reiserfsprogs
- [x] rfkill
- [x] sg3-utils
- [x] shadow
- [x] smartmontools
- [x] sudo
- [x] sysfsutils
- [x] trousers
- [x] xfsprogs

#### core-base

- [x] aosc-aaa
- [x] bash
- [x] gcc-runtime
- [x] zlib

#### debug-base

- [x] cgdb
- [x] gdb
- [x] strace
- [x] valgrind

#### devel-base

- [x] autoconf
- [x] automake
- [x] binutils
- [x] bison
- [x] cmake
- [x] diffutils
- [x] flex
- [x] gawk
- [x] gcc
- [x] gettext
- [x] groff
- [x] help2man
- [x] libtool
- [x] m4
- [x] make
- [x] meson
- [x] ninja
- [x] patch
- [x] pkg-config
- [x] sed
- [x] texinfo

#### editor-base

- [x] ed
- [x] nano

#### network-base

- [x] arp-scan
- [x] bind
- [x] bluez
- ~clash~ (blocked by Go, no architectural support)
- [x] dhcp
- [x] dnsmasq
- [x] ethtool
- [x] geoip-api-c
- [x] iana-etc
- [x] idnkit
- [x] inetutils
- [x] iproute2
- [x] iptables
- [x] iw
- [x] lksctp-tools
- [x] mtr
- [x] netcat
- [x] net-tools
- [x] nfs-utils
- [x] nghttp2
- [x] openssh
- [x] ppp
- [x] proxychains-ng
- [x] rsync
- [x] shadowsocks-libev
- ~v2ray~ (blocked by Go, no architectural support)
- [x] wireless-tools
- [x] wpa-supplicant

#### python-base

- ~pip~ (blocked by Rust, `setuptools-rust`)
- [x] python-2
- [x] python-3
- [x] virtualenv

#### systemd-base

- [x] modemmanager
- [x] networkmanager

#### util-base

- [x] arch-chroot
- ~bat~ (no working Rust version, see below)
- [x] bzip2
- [x] convmv
- [x] coreutils
- [x] cpio
- [x] diffutils
- [x] dos2unix
- [x] elfutils
- [x] expect
- ~fd~ (no working Rust version, see below)
- [x] file
- [x] findutils
- [x] gawk
- [x] gpm
- [x] grep
- [x] groff
- [x] gzip
- [x] hdparm
- [x] htop
- [x] iotop
- [x] kbd
- [x] kmod
- [x] less
- [x] libarchive
- [x] lm-sensors
- [x] lrzip
- [x] lsb-release
- [x] lshw
- [x] lsof
- [x] lz4
- [x] lzip
- [x] lzo
- [x] lzop
- [x] man-db
- [x] man-pages
- [x] nano
- [x] neofetch
- [x] nethogs
- [x] newt
- [x] p7zip
- [x] patch
- [x] pciutils
- [x] procps
- [x] progress
- [x] psmisc
- [x] pv - `src/library/getopt.o: ABI is incompatible with that of the selected emulation` (worked around)
- ~ripgrep~ (no working Rust version, see below)
- [x] screen
- [x] sdparm
- [x] sed
- [x] tar
- [x] texinfo
- [x] tmux
- [x] tree
- [x] unrar
- [x] unzip
- [x] usbutils
- [x] util-linux
- [x] which
- [x] xz
- [x] zip

#### web-base

- [x] curl
- [x] w3m
- [x] wget

#### Extra Packages

- [x] acbsThough
- [x] autobuild3
- [x] git

*Issues, problem, and errors encountered during this build will be recorded in the comments below.*

**Comment by Cyanoxygen** [comment]
### List of partially built packages 

- pkg-config (missing glib, using internal glib)
- xz (missing po4a, disabling i18nlized docs; disabling RECONF as workaround)
- python3 (bootstrap stage, drop most BUILDDEPS)
- ca-certs needs new make-ca script from LFS (now uses SSLDIR to install directly to target dir)
- gettext: drop glib and libcroco
- libidn2: disable-gtk-doc
- python-3: incredibly slow byte code precompiling, not sure whether it's on qemu or py3 - forcibly disabling byte code precompiling to workaround
- openssh: depends on libfido2 -> libusb -> systemd, using retro DEPs
- bind: using retro DEPs
- ijs: drop ghostscript (dependency loop)
- ghostscript: disable parallel build
- various other packages used Retro recipes. See `git diff`.

**Comment by MingcongBai** [comment]
Partially built packages and their respective changes are to be recorded in Autobuild3's upcoming stage2 mode configurations, denominated with `.stage2` suffixes.

**Comment by Cyanoxygen** [comment]
pACBS status - might just keep it locally. update is unnecessary.

upper-left: goal: gtk-3
upper-right: valgrind, gdb - blocked by boost
lower-left: 
lower-right: boost goal: lvm2

**Comment by MingcongBai** [comment]
> pACBS status - might just keep it locally. update is unnecessary.
> 
> upper-left: python-3 upper-right: swig (finished) lower-left: libedit libevent libidn lower-right: joe (finished)

Yeah I would just leave these details in a local document.

**Comment by Cyanoxygen** [comment]
### DEPs of apt:

- [x] dpkg
- [x] zlib
- [x] bzip2
- [x] glibc
- [x] curl
- [x] gnutls
- [x] lz4
- [x] zstd
- [x] libunistring
- [x] xxhash

- python-3: read the first comment for details.

gnome build queue:

doxygen cario gobject-introspection pango (update when build finished)

**Comment by MingcongBai** [comment]
Recipe for BuildKit
---------------------------

### admin-base

- [ ] apt
- [ ] apt-file
- [ ] atm
- [ ] bcache-tools
- [ ] btrfs-progs
- [ ] core-base
- [ ] cryptsetup
- [ ] dbus
- [ ] debianutils
- [ ] dosfstools
- [ ] e2fsprogs
- [ ] exfat-utils
- [ ] f2fs-tools
- [ ] fcron
- [ ] fuse
- [ ] genfstab
- [ ] gnupg
- [ ] gpart
- [ ] gptfdisk
- [ ] hddtemp
- [ ] hfsprogs
- [ ] jfsutils
- [ ] kernel-tools
- [ ] mdadm
- [ ] mtd-utils
- [ ] multipath-tools
- [ ] nvme-cli
- [ ] os-prober
- [ ] parted
- [ ] polkit
- [ ] powertop
- [ ] quota-tools
- [ ] reiserfsprogs
- [ ] rfkill
- [ ] sg3-utils
- [ ] shadow
- [ ] smartmontools
- [ ] sudo
- [ ] sysfsutils
- [ ] trousers
- [ ] xfsprogs

### core-base

- [ ] aosc-aaa
- [ ] bash
- [ ] gcc-runtime
- [ ] zlib

### debug-base

- [ ] cgdb
- [ ] gdb
- [ ] strace
- [ ] valgrind

### devel-base

- [ ] autoconf
- [ ] automake
- [ ] binutils
- [ ] bison
- [ ] cmake
- [ ] diffutils
- [ ] flex
- [ ] gawk
- [ ] gcc
- [ ] gettext
- [ ] groff
- [ ] help2man
- [ ] libtool
- [ ] m4
- [ ] make
- [ ] meson
- [ ] ninja
- [ ] patch
- [ ] pkg-config
- [ ] sed
- [ ] texinfo

### editor-base

- [ ] ed
- [ ] nano

### network-base

- [ ] arp-scan
- [ ] bind
- [ ] bluez
- [ ] clash
- [ ] core-base
- [ ] dhcp
- [ ] dnsmasq
- [ ] ethtool
- [ ] geoip-api-c
- [ ] iana-etc
- [ ] idnkit
- [ ] idnkit
- [ ] inetutils
- [ ] iproute2
- [ ] iptables
- [ ] iw
- [ ] lksctp-tools
- [ ] mtr
- [ ] netcat
- [ ] net-tools
- [ ] nfs-utils
- [ ] nghttp2
- [ ] openssh
- [ ] ppp
- [ ] proxychains-ng
- [ ] rsync
- [ ] shadowsocks-libev
- [ ] v2ray
- [ ] wireless-tools
- [ ] wpa-supplicant

### python-base

- [ ] pip
- [ ] python-2
- [ ] python-3
- [ ] virtualenv

### systemd-base

- [ ] modemmanager
- [ ] networkmanager

### util-base

- [ ] arch-chroot
- [ ] bat
- [ ] bzip2
- [ ] convmv
- [ ] core-base
- [ ] coreutils
- [ ] cpio
- [ ] diffutils
- [ ] dos2unix
- [ ] elfutils
- [ ] expect
- [ ] fd
- [ ] file
- [ ] findutils
- [ ] gawk
- [ ] gpm
- [ ] grep
- [ ] groff
- [ ] gzip
- [ ] hdparm
- [ ] htop
- [ ] iotop
- [ ] kbd
- [ ] kmod
- [ ] less
- [ ] libarchive
- [ ] lm-sensors
- [ ] lrzip
- [ ] lsb-release
- [ ] lshw
- [ ] lsof
- [ ] lz4
- [ ] lzip
- [ ] lzo
- [ ] lzop
- [ ] man-db
- [ ] man-pages
- [ ] nano
- [ ] neofetch
- [ ] nethogs
- [ ] newt
- [ ] p7zip
- [ ] patch
- [ ] pciutils
- [ ] procps
- [ ] progress
- [ ] psmisc
- [ ] pv
- [ ] ripgrep
- [ ] screen
- [ ] sdparm
- [ ] sed
- [ ] tar
- [ ] texinfo
- [ ] tmux
- [ ] tree
- [ ] unrar
- [ ] unzip
- [ ] usbutils
- [ ] util-linux
- [ ] which
- [ ] xz
- [ ] zip

### web-base

- [ ] curl
- [ ] w3m
- [ ] wget

### Extra Packages

- [ ] acbs
- [ ] autobuild3
- [ ] git

**Comment by MingcongBai** [comment]
`ca-certs` need a new `make-ca` script for compatibility with newer Perl.

**Comment by Cyanoxygen** [comment]
Rust toolchain building progress
-----

This comment tracks the progress of bringing the Rust toolchain to this target.

Stage 1
- [x] amd64 to mips64r6el cross-build GCC
- [x] amd64 to mips64r6el cross-build rustc

Stage 2
- [ ] mips64r6el Native Rust toolchain

Stage 3
- [ ] Build with ACBS Tree

**Comment by MingcongBai** [comment]
> ## Rust toolchain building progress
> 
> This comment tracks the progress of bringing the Rust toolchain to this target.
> 
> Stage 1
> 
>     * [x]  amd64 to mips64r6el cross-build GCC
> 
>     * [x]  amd64 to mips64r6el cross-build rustc
> 
> 
> Stage 2
> 
>     * [ ]  mips64r6el Native Rust toolchain
> 
> 
> Stage 3
> 
>     * [ ]  Build with ACBS Tree

Skipping Rust fpr stage 2. No usable version.

1. Last known version according to CIP employees was 1.55.0, "1.56.0 just crashes." No further information provided.
2. Versions 1.55.0 - 1.59.0 requires backporting [Pull Request #90001 from the upstream](https://github.com/rust-lang/rust/pull/90001).
3. Versions 1.55.0 - 1.56.0 no longer builds due to missing `std` crate from Cargo registry.
4. Version 1.55.0 (available from [CIP](https://repo.oss.cipunited.com/rust/stable/1.55.0/)) could not be used to bootstrap >= 1.57.0 due to unsatisfied `edition2021` requirement.
5. Version 1.60.0 would not build with GCC 12.2.0 due to ABI changes in `libgcc_s` and `libstdc++`.
6. Versions 1.61.0 - 1.64.0 cross toolchain (x86_64 => mipsisa64r6el) built successfully, but fails to generate a native toolchain (`bootstrap` module fails with Code 11 segmentation fault - illegal memory access).

**Comment by MingcongBai** [comment]
Adjusting recipes to make leave out all Rust requirements.

**Comment by MingcongBai** [comment]
In a conversation with @wzssyqa, who originally ported Rust to MIPS r6.

```
Mingcong Bai, [2022/10/24 上午8:41]
强哥，我们这里构建 Rust 遇到了一些疑似 codegen 方面的 regression（假设当时 1.55.0 是可用的
[ YunQiang, we have ran into some issues while building Rust. I suspect that it's related to a regression in the codegen (assuming that 1.55.0 was usable. ]

Mingcong Bai, [2022/10/24 上午8:41]
一开始以为是 Qemu user 的问题，但在 system 里也复现了
[ We initially thought that this was a problem with Qemu's user emulation, but we also reproduced this in system. ]

Mingcong Bai, [2022/10/24 上午8:42]
不是很清楚如何调试，所以我们目前准备从 1.55 开始按版本测试，确定下出问题的范围；此外就可能真的需要一些指引了
[ Not sure how to debug this. Therefore, we are going to test each stable release from 1.55.0 to narrow the problem down to a range of versions... Any guidance would be appreciated. ]

YunQiang Su, [2022/10/24 下午4:31]
嗯，当时的版本估计也不行
[ Well, I think that those versions from before never worked. ]

Mingcong Bai, [2022/10/24 下午5:25]
[In reply to YunQiang Su]
从来没能编译过？
[ Like it never worked? ]

YunQiang Su, [2022/10/24 下午5:33]
一直能cross出来，就是运行的确很久了，有问题
[ The cross toolchain always built, but it does have issues during runtime for a long while now. ]

YunQiang Su, [2022/10/24 下午5:33]
但是没深入研究
[ We have yet to look into this further. ]
```

**Comment by MingcongBai** [comment]
Building a full system without Rust is highly problematic, not only do we miss out on any sort of Mozilla support, one key component to our maintenance toolkit - [Ciel](https://github.com/AOSC-Dev/ciel-rs) (written in Rust), will not build.

Since we are building via Qemu user now, we can just use Ciel installed on our AMD64 build hosts.

**Comment by MingcongBai** [comment]
Advice from @liushuyu.

```
子兴 刘, [2022/10/25 下午10:51]
[In reply to Mingcong Bai]
建议检查一下里面的那个 bootstrap 出现了什么问题
因为现在还无法确认是 qemu 还是 LLVM 的问题
[ I'd suggest that we check out what is wrong with the bootstrap module. It's difficult to know whether the issue lies in Qemu or LLVM. ]

子兴 刘, [2022/10/25 下午10:51]
如果确认是 LLVM 的问题，那么需要检查是什么样的代码导致 IR -> 机器码 下降错误
[ If we are sure that it's an issue with LLVM, we need to check what codegen resulted in an error in the IR => machine code. ]

子兴 刘, [2022/10/25 下午10:52]
（如果是 qemu 的问题，一样需要检查是不是 MIPS -> TCG IR -> 机器码 中间，一个或多个环节存在下降错误）
[ If it's a problem with Qemu, we still need to check whether this is due to procedural issues in one or more of the MIPS => TCG => machine code translation. ]

子兴 刘, [2022/10/25 下午10:59]
关于调试的办法：使用支持 mips64r6 的调试器（gdb-multihead 或者 lldb）去连接 qemu 的调试端口（使用 qemu 的 gdb-stub 功能）
然后检查是什么地方出现了段错误
[ As for how to debug - get a mips64r6 debugger (gdb-multihead or lldb) and connect it to Qemu's debugging interface (using Qemu's gdb-stub function). ]

子兴 刘, [2022/10/25 下午11:00]
gdb 可能会无法读取调试符号，因为这个情况下调试过程实际上是 qemu 在代理
gdb 只是在给 qemu 发送调试命令
这个情况下，可以让 gdb 单独从目标二进制（文件）读取调试符号
[ GDB may not be able to read debug symbols, because this process is handled by Qemu. GDB only sends debugger instructions to Qemu. In this case, we can make GDB read the debug symbols from standalone target binary files. ]
```

**Comment by MingcongBai** [comment]
@liushuyu May help debugging this issue down the line.

**Comment by MingcongBai** [comment]
This marks the conclusion to Stage 2.
